export const routes = {
  SIGN_UP: '/sign-up',
  CONFIRM_EMAIL: '/confirm-email',
  ACCEPT_INVITATION: '/accept-invitation',
  SIGN_IN: '/sign-in',
  FORGOT_PASSWORD: '/forgot-password',
  MAIL_CHANGE_PASSWORD: '/mail-change-password',
  CHANGE_PASSWORD: '/change-password',
  API: '/api',
  USER: '/user',
  ROOM: '/room',
  CREATE: '/create',
  ADD_USER_TO_ROOM: '/add-user-to-room',
  GET_ROOM: '/get-room',
  DEFAULT: '/',
  MESSAGE: '/message',
};
